project:
  type: book

book:
  title: "Papers Review"
  subtitle: "Revisión de articulos cientificos para el estudio de las ciudades"
  author:
    - name: Jorge Aravena Peña
      url: https://jap-port.vercel.app/
      affiliation: Centro de Inteligencia Territorial
      affiliation-url: https://cit.uai.cl
      email: [jorge.aravena.p@uai.cl]
  date: "2026-01-29"
  #number-sections: 3
  page-footer: 
    left: "Copyright 2026, Jorge Aravena Peña | Idea original: [Denis Berroeta](https://github.com/DenisSebastian/book-papers-GEOAI)"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Revisiones de Papers"
      chapters:
        - liao-2023.qmd
    - references.qmd
  appendices:
    - template_paper.qmd

bibliography: references.bib
cite-method: citeproc
lang: es

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "denis.berroeta@uai.cl"
    toc-title: "Contenidos"
  
execute:
  warning: false
  
editor: source
always_allow_html: true



