project:
  type: book
  output-dir: docs

book:
  title: "Papers Review"
  subtitle: "Revisi칩n de articulos cientificos para el estudio de las ciudades"
  author:
    - name: Jorge Aravena Pe침a
      url: https://jap-port.vercel.app/
      email: [jorge.aravena.p@uai.cl]
  date: "2026-01-28"
  #number-sections: 3
  page-footer: 
    left: "Copyright 2026, Jorge Aravena Pe침a | Idea original: [Denis Berroeta](https://github.com/DenisSebastian/book-papers-GEOAI)"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Revisi칩n de Papers"
      chapters:
        - liao-2023.qmd
    - references.qmd
  appendices:
    - template_paper.qmd

bibliography: references.bib
cite-method: citeproc
lang: es

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "[jorge.aravena.p@uai.cl]"
    toc-title: "Contenidos"
  
execute:
  warning: false
  
editor: source
always_allow_html: true



